---

- name: Configure Debian Dev Box VM
  hosts: dev_box_vms

  vars:
    brew_path: /home/linuxbrew/.linuxbrew
    user_name: dgf

  roles:
    - box
    - podman

  tasks:
    - name: Install Homebrew packages
      community.general.homebrew:
        update_homebrew: true
        name:
          - golang

    - name: Git config
      copy:
        dest: ~/.gitconfig
        content: |

          [core]
            pager = delta

          [interactive]
            diffFilter = delta --color-only

          [delta]
            side-by-side = true
            line-numbers = true
            navigate = true # use n and N to move between diff sections

          [merge]
            conflictStyle = zdiff3

          [filter "lfs"]
            clean = git-lfs clean -- %f
            smudge = git-lfs smudge -- %f
            process = git-lfs filter-process
            required = true

