---

- name: Configure Debian Dev Box VM
  hosts: dev_box_vms

  vars:
    brew_path: /home/linuxbrew/.linuxbrew
    user_name: dgf

  roles:
    - box
    - podman

  tasks:
    - name: Install Homebrew packages
      community.general.homebrew:
        update_homebrew: true
        name:
          - golang

