- name: Configure Debian Dev Box VM
  hosts: debian-dev-box

  vars:
    brew_path: /home/linuxbrew/.linuxbrew
    user_name: dgf

  tasks:

    - name: Ensure package lists are updated
      become: true
      apt:
        update_cache: yes

    - name: Install essential work tools
      become: true
      apt:
        name:
          - build-essential
          - curl
          - dnsutils
          - git
          - iputils-ping
          - net-tools
          - nftables
          - telnet
          - uidmap
        state: present

    - name: Ensure we are actually on Trixie
      shell: cat /etc/debian_version
      register: deb_version
      changed_when: false

    - name: Show Debian Version
      debug:
        msg: The VM is running Debian version {{ deb_version.stdout }}

    - name: Apply SSH Performance Tuning
      become: true
      notify: Restart SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
        state: present
        validate: '/usr/sbin/sshd -t -f %s'
      loop:
        - { regexp: '^#?UseDNS', line: 'UseDNS no' }
        - { regexp: '^#?UsePAM', line: 'UsePAM no' }
        - { regexp: '^#?GSSAPIAuthentication', line: 'GSSAPIAuthentication no' }
        - { regexp: '^#?AddressFamily', line: 'AddressFamily inet' }
        - { regexp: '^#?X11Forwarding', line: 'X11Forwarding no' }

    - name: Enable Linger for user
      become: true
      ansible.builtin.command: /usr/bin/loginctl enable-linger {{ user_name }}
      args:
        creates: /var/lib/systemd/linger/{{ user_name }}

    - name: Virtiofs mount
      become: true
      block:

        - name: Create share directory
          ansible.builtin.file:
            path: /share
            state: directory
            mode: a=rx,u+w
          notify:
            - Mount Share

        - name: Configure share mount
          ansible.builtin.lineinfile:
            path: /etc/fstab
            regexp: '^share '
            line: 'share /share virtiofs rw,nofail 0 0'
            state: present
          notify:
            - Daemon Reload
            - Mount Share

    - name: Check if Homebrew is installed
      ansible.builtin.stat:
        path: '{{ brew_path }}'
      register: brew_stat

    - name: Install Homebrew
      ansible.builtin.shell: |
        NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: not brew_stat.stat.exists

    - name: Install Homebrew packages
      community.general.homebrew:
        update_homebrew: true
        name:
          - antidote
          - bat
          - byobu
          - dive
          - eza
          - fzf
          - git
          - go-task
          - golang
          - htop
          - jq
          - ncdu
          - neovim
          - node@18
          - oh-my-posh
          - openjdk@21
          - podman-compose
          - tig
          - tokei
          - yq
          - zoxide
          - zsh
          - zsh-autosuggestions
          - zsh-completions

    - name: Change route of Podman pasta network
      block:

        - name: Create containers conf directory
          ansible.builtin.file:
            path: "{{ brew_path }}/etc/containers/containers.conf.d"
            state: directory
            mode: a=rx,u+w

        - name: Configure nftables
          ansible.builtin.copy:
            dest: "{{ brew_path }}/etc/containers/containers.conf.d/network.conf"
            content: |
              [network]
              firewall_driver="nftables"

    - name: Set user shell to zsh
      become: true
      ansible.builtin.user:
        name: '{{ user_name }}'
        shell: '{{ brew_path }}/bin/zsh'

    - name: Configure Z shell
      notify: Zsh compinit
      block:

        - name: Create Zsh config directory
          ansible.builtin.file:
            path: ~/.zsh
            state: directory

        - name: Deploy Zsh environment
          ansible.builtin.copy:
            dest: ~/.zshenv
            content: |
              export ZSH=$HOME/.zsh

              eval "$({{ brew_path }}/bin/brew shellenv)"

              if type brew &>/dev/null; then
                eval "$({{ brew_path }}/bin/fzf --zsh)"
                eval "$({{ brew_path }}/bin/oh-my-posh init zsh --config gruvbox)"
                eval "$({{ brew_path }}/bin/zoxide init --cmd cd zsh)"
              fi

        - name: Deploy Zsh resource config
          ansible.builtin.copy:
            dest: ~/.zshrc
            content: |
              HISTSIZE=999999999
              SAVEHIST=$HISTSIZE
              HISTFILE=~/.history

              setopt AUTO_CD
              setopt EXTENDED_HISTORY
              setopt HIST_IGNORE_ALL_DUPS
              setopt HIST_IGNORE_SPACE
              setopt HIST_NO_FUNCTIONS
              setopt HIST_NO_STORE
              setopt HIST_REDUCE_BLANKS
              setopt INC_APPEND_HISTORY
              setopt NO_HIST_BEEP
              setopt SHARE_HISTORY

              if type brew &>/dev/null; then
                FPATH="$(brew --prefix)/share/zsh-completions:$FPATH"
                source "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"

                autoload -Uz compinit
                compinit
              fi

              autoload -U up-line-or-beginning-search
              autoload -U down-line-or-beginning-search
              zle -N up-line-or-beginning-search
              zle -N down-line-or-beginning-search
              bindkey "^[[A" up-line-or-beginning-search # Up
              bindkey "^[[B" down-line-or-beginning-search # Down

              alias l="eza --all --long --no-user --git --icons=always --mounts"
              alias ll="eza --all --group --long --git --icons=always --mounts --time-style=long-iso"
              alias lt="eza --long --no-user --git --icons=always --tree"
              alias vim=nvim

    - name: Clone LazyVim starter
      ansible.builtin.git:
        depth: 1
        dest: /home/{{ user_name }}/.config/nvim
        repo: https://github.com/LazyVim/starter
        single_branch: yes
        version: main
        update: false

    - name: Configure LazyVim colorscheme
      ansible.builtin.copy:
        src: nvim-plugin-colorscheme.lua
        dest: /home/{{ user_name }}/.config/nvim/lua/plugins/colorscheme.lua
        owner: '{{ user_name }}'
        group: '{{ user_name }}'
        mode: a=,u+rw

  handlers:

    - name: Restart SSH
      become: true
      ansible.builtin.service:
        name: ssh
        state: restarted

    - name: Daemon Reload
      become: true
      ansible.builtin.command: /usr/bin/systemctl daemon-reload

    - name: Mount Share
      become: true
      ansible.builtin.command: mount /share

    - name: Zsh compinit
      ansible.builtin.command: rm -f ~/.zcompdump; compinit

