---

- name: Install Homebrew CLI packages
  homebrew:
    update_homebrew: true
    name:
      - bat
      - byobu
      - dive
      - git
      - git-delta
      - git-lfs
      - golang
      - htop
      - jq
      - ncdu
      - node@18
      - openjdk@21
      - tig
      - tokei
      - yq

- name: Fix Byobu and tmux color mode
  block:

    - name: Create config directory
      file:
        state: directory
        path: '~/.config/{{ item }}'
      loop:
        - tmux
        - byobu

    - name: Configure Byobu
      copy:
        dest: '~/.config/byobu/.tmux.conf'
        content: |
          set -g set-clipboard on
          set-option -ga terminal-overrides ",xterm-256color:Tc"

    - name: Configure tmux
      copy:
        dest: '~/.config/tmux/tmux.conf'
        content: |
          set -g set-clipboard on
          set-option -ga terminal-overrides ",xterm-256color:Tc"

