---

- name: Install Homebrew CLI packages
  homebrew:
    update_homebrew: true
    name:
      - bat
      - byobu
      - dive
      - git
      - golang
      - htop
      - jq
      - ncdu
      - node@18
      - openjdk@21
      - tig
      - tokei
      - yq

- name: Fix Byobu and tmux color mode
  block:

    - name: Create config directory
      file:
        state: directory
        path: '~/.config/{{ item }}'
      loop:
        - tmux
        - byobu

    - name: Set terminal-overrides options
      copy:
        dest: '~/.config/{{ item }}/.tmux.conf'
        content: |
          set-option -ga terminal-overrides ",xterm-256color:Tc"
      loop:
        - tmux
        - byobu

