---

- name: Install Homebrew Lazy tools
  homebrew:
    update_homebrew: true
    name:
      - fd
      - lazygit
      - neovim
      - ripgrep

- name: Clone LazyVim starter
  git:
    depth: 1
    dest: ~/.config/nvim
    repo: https://github.com/LazyVim/starter
    single_branch: yes
    version: main
    update: false

- name: Copy LazyVim options
  copy:
    src: lazy-options.lua
    dest: ~/.config/nvim/lua/config/options.lua

- name: Copy LazyVim colorscheme
  copy:
    src: lazy-gruvbox.lua
    dest: ~/.config/nvim/lua/plugins/gruvbox-colorscheme.lua
